pool:
  vmImage: 'windows-latest'

resources:
 repositories:
   - repository: DemoApiTesting
     type: git
     name: DevSecOps/Demo-Api-testing
     ref: refs/heads/main
     endpoint: Demo-Api-testing-claims
     clean: true

steps:
  - checkout: DemoApiTesting  # Clona el repo antes de usarlo
  - script: ls -R  # Lista todos los archivos para verificar si están disponibles


extends:
  template: 'azure-pipelines.yml@DemoApiTesting'