pool:
  name: 'AXA COLPATRIA_WebSite'

resources:
  repositories:
    - repository: periferiait-template-pipeline  # Alias del repo
      type: git
      name: DevSecOps/periferiait-template-pipeline  # Nombre del repo en Azure DevOps
      ref: refs/heads/develop
      endpoint: Demo-Api-testing-claims

extends:
  template: 'azure-pipelines-democorporativo.yml@periferiait-template-pipeline'
