pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: DemoApiTesting
      type: git
      name: DevSecOps/Demo-Api-testing
      ref: main  # <-- Se cambió de 'refs/heads/main' a 'main'
      clean: true  # <-- Se fuerza a obtener siempre la última versión

steps:
  - checkout: DemoApiTesting  # <-- Se clona el repo antes de usarlo
  - script: ls -R  # <-- Se listan los archivos para verificar si están accesibles

extends:
  template: azure-pipelines.yml@DemoApiTesting  # <-- Se mantiene la referencia al pipeline general
