pool:
  vmImage: 'windows-latest'

resources:
 repositories:
   - repository: DemoApiTesting
     type: git
     name: DevSecOps/Demo-Api-testing
     ref: refs/heads/main
     

extends:
  template: azure-pipelines.yml@DemoApiTesting