pool:
  vmImage: 'windows-latest'

resources:
 repositories:
   - repository: azure-pipelines-democorporativo.yml
     type: git
     name: DevSecOps/azure-pipelines-democorporativo.yml
     ref: refs/heads/main
     endpoint: Demo-Api-testing-claims
    
     

extends:
  template: 'azure-pipelines-democorporativo.yml@periferiait-template-pipeline'