pool:
  vmImage: 'windows-latest'

resources:
 repositories:
   - repository: Demo-Api-testing
     type: git
     name: DevSecOps/Demo-Api-testing
     ref: refs/heads/main

extends:
  template: azure-pipelines.yml@Demo-Api-testing